> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Using Numpy to work with arrays


### Numpy is a python library that provides a multidimentional array object, dericed objects and fast opperation on arrays.  

For this assignment I will look how to use numpy in order to work with numbers and arrays. By going through the [documentation](https://numpy.org/doc/stable/contents.html) and pick a few functions to try using. For this assignment I chose the following functions:

#### Function 1
- Empty
    - This function creates an array of a given shape without initializing the entries
    
#### Function 2
- Matmul
    - This function multiplies togeather each element of two arrays
    
#### Function 3
- Sqrt
    - This function takes the square root of each element in an array
    
#### Function 4
- Sum
    - This function sums up the elements in an array based on an axis
    
#### Function 5
- Round
    - This funcion rounds a floating point number to a given decimal point

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "joeolafs/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/joeolafs/numpy-array-operations


'https://jovian.ai/joeolafs/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [60]:
# List of functions explained 
function1 = np.empty #Creates uninitialized arrays
function2 = np.matmul #multiplies two arrays together
function3 = np.sqrt #takes square root of each number
function4 = np.sum #Sum of array elements over a given axis
function5 = np.round #Rounds the floating point number 

## Function 1 - Empty

np.empty(shape, dtype=float, order='C', *, like=None)

This function creates an array with a given shape, but without initializing the elements. The numbers occupying the array are arbitrary data. The values must be set manually by the user, this should be used with caution.

In [46]:
# Example 1 - working with concatinate
arr_empty = np.empty([3,2])

arr_empty

array([[3.16227766, 3.87298335],
       [5.09901951, 1.24498996],
       [1.4832397 , 9.        ]])

This function outputs an array of the shape [3,2].

In [49]:
# Example 2 - working
arr_empty2 = np.empty([5], dtype=int)

arr_empty2

array([-180972272,        538,          0,          0,     131074])

The function also allows you to chose the type of inputs into the output array, in this case an 'int'.

In [50]:
# Example 3 - breaking (to illustrate when it breaks)
arr_err = np.empty([2,3,2], dtype=INT)

NameError: name 'INT' is not defined

Explanation about example (why it breaks and how to fix it)

Example 3 shows that the empty function can break if there is a spelling error in the 'dtype'. This can be fixed by being careful when writing up the function.


Some closing comments about when to use this function.

This function is a quick way to create arrays but it can be dangerous because it does not initialize the values and they must be set manually.

In [51]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "joeolafs/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/joeolafs/numpy-array-operations


'https://jovian.ai/joeolafs/numpy-array-operations'

## Function 2 - Matmul

np.matmul(x1, x1, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[,signature,extobj])

This method multiplies together two arrays in this demonstration

In [12]:
# Example 1 - working
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[10, 20],
                 [30, 40]])

np.matmul(arr1, arr2)

array([[ 70, 100],
       [150, 220]])

This example multiplies together each element in the arrays and creates an array in the same shape.

In [52]:
# Example 2 - working
arr1 = np.array([10, 10])
arr2 = np.array([[1, 2],
                 [3, 4]])

np.matmul(arr1, arr2)

array([40, 60])

This example multiplies element [0] in arr1 with each element in column 0 in arr2 and element [1] in arr1 with each element in column 1 in arr2. Then it adds up the sum and creates an array in the same shape as arr1.

In [17]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([1, ])
arr2 = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])
np.matmul(arr1, arr2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

Explanation about example (why it breaks and how to fix it)

This function breaks if one array is not full and therefor it is not possible to multiply the two arrays together. You can solve this by removing the [1] element of arr1.

Some closing comments about when to use this function.

You use this function when you need to know the multiplication between all elements of two arrays

In [22]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "joeolafs/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/joeolafs/numpy-array-operations


'https://jovian.ai/joeolafs/numpy-array-operations'

## Function 3 - SQRT

np.sqrt(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Takes a square root of each element in an array

In [19]:
# Example 1 - working
arr1 = np.array([1, 4, 9])

np.sqrt(arr1)

array([1., 2., 3.])

This example show how the function takes the square root of each element in the array.

In [20]:
# Example 2 - working
arr1 = np.array([[10, 15, 26],
                 [1.55, 2.2, 81]])
np.sqrt(arr1)

array([[3.16227766, 3.87298335, 5.09901951],
       [1.24498996, 1.4832397 , 9.        ]])

This example shows how the function takes the square root of each element in a matrix

In [21]:
# Example 3 - breaking (to illustrate when it breaks)
np.sqrt(-1)

<ipython-input-21-e40eb7dbd6a8>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


nan

Explanation about example (why it breaks and how to fix it)

This function breaks when you attempt to take the square root of a negative number because that is impossiple. It is possible to change the function to np.sqrt(1**-0.5) and receive 1 but in general squares can not be negative numbers and therefore you can not take the root of a negative

Some closing comments about when to use this function.

This function is useful when calculating the angle of a graph or when you are working with numbers and need the square root of them

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "joeolafs/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/joeolafs/numpy-array-operations


'https://jovian.ai/joeolafs/numpy-array-operations'

## Function 4 - Sum

numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    
This function adds to gether all elements of an array over a given axis

In [27]:
# Example 1 - working
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
np.sum(arr, axis=0)

array([12, 15, 18])

This example shows how the function adds up the elements on axis 0.

In [28]:
# Example 2 - working
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
np.sum(arr, axis=1)

array([ 6, 15, 24])

This example shows how the function adds up the elements on axis 1.

In [36]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([[1, 2, 3],
                [4, np.nan, 6],
                [7, 8, 9]])
np.sum(arr, axis=0)

array([12., nan, 18.])

Explanation about example (why it breaks and how to fix it)

This function can break if the data is not complete, meaning there are numbers missing, filled in with np.nan for this example. This can be fixed by using the np.nansum() function which ignores empty elements:

In [38]:
arr = np.array([[1, 2, 3],
                [4, np.nan, 6],
                [7, 8, 9]])

np.nansum(arr, axis=0)

array([12., 10., 18.])

Some closing comments about when to use this function.

This function is useful to calculate the totals in an array

In [53]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "joeolafs/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/joeolafs/numpy-array-operations


'https://jovian.ai/joeolafs/numpy-array-operations'

## Function 5 - Round_

np.round_(a, decimals=0, out=None)
This method rounds a floating number to a certain number of decimal points

In [55]:
# Example 1 - working
arr1 = np.array([1.3344566, 23.23453456, 8.64356783546323456])

np.round(arr1)

array([ 1., 23.,  9.])

Rounds each element of the array down to the nearest whole number

In [57]:
# Example 2 - working
arr1 = np.array([1.3344566, 23.23453456, 8.64356783546323456])

np.round(arr1, decimals=3)

array([ 1.334, 23.235,  8.644])

Rounds each element in the array to a given nunmber of decimal point

In [58]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([1.3344566, 23.23453456, 8.64356783546323456])

np.round(arr1, decimal= -2)

TypeError: _around_dispatcher() got an unexpected keyword argument 'decimal'

Explanation about example (why it breaks and how to fix it)

This example is to show that it is not possible to round to a negative number of decimal points

Some closing comments about when to use this function.

This function can be very useful when you need to display the data in a presentable way, when each number has many decimal points. Can quickly round each element in the array.

In [59]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "joeolafs/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/joeolafs/numpy-array-operations


'https://jovian.ai/joeolafs/numpy-array-operations'

## Conclusion

This notebook covers five functions that NumPy has to offer. It offers simple examples of how to use each of the functions. For more information please read more on the following links.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Numpy official documentation : https://numpy.org/doc/stable/contents.html
* Numpy empty function : https://numpy.org/doc/stable/reference/generated/numpy.empty.html?highlight=empty#numpy.empty
* Numpy matmul function : https://numpy.org/doc/stable/reference/generated/numpy.matmul.html?highlight=matmul#numpy.matmul
* Numpy sqrt function : https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html?highlight=sqrt#numpy.sqrt
* Numpy sum function : https://numpy.org/doc/stable/reference/generated/numpy.sum.html#numpy.sum
* Numpy round function : https://numpy.org/doc/stable/reference/generated/numpy.round_.html?highlight=round#numpy.round_

In [61]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "joeolafs/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/joeolafs/numpy-array-operations


'https://jovian.ai/joeolafs/numpy-array-operations'

In [62]:
jovian.submit(assignment="zero-to-pandas-a2")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "joeolafs/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/joeolafs/numpy-array-operations
[jovian] Submitting assignment..
[jovian] Verify your submission at https://jovian.ai/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations


In [63]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "joeolafs/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/joeolafs/numpy-array-operations


'https://jovian.ai/joeolafs/numpy-array-operations'